### ISSUE TITLE
Stat not working for loki datasouce

### ISSUE THREAD

**Issue by emouawad** [K-Phoen/dark#236]
Stat Not working for loki datasource / targets.
Maybe i missed that part in the documentation, is there somewhere  the supported features (grafana ui components) are located?

```yaml
- stat:
    title: Total
    targets:
      - prometheus:
          query: metric-A{app="app"}

- stat:
    title: Total 2
    datasource: loki
    targets:
      - loki:
          query: metric-B{app="app"}       
```
